spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    ddl-auto: none
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      javax:
        persistence:
          validation:
            mode: none
  thymeleaf:
    cache: false
  devtools:
    remote:
      secret: somesecret
    livereload:
      enabled: true
  resources: 
    chain:
      cache: false
      strategy:
        fixed: 
          enabled: true
          version: test_version