version: 2
jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test

      - run: gradle assemble

      - run: sudo docker login $DOCKER_USERNAME $DOCKER_PASSWORD https://hub.docker.com

      - run: sudo docker build -f ci-runner.docker -t aceleradora-tw/esqueleto-ci-runner .

      - run: sudo docker push aceleradora-tw/esqueleto-ci-runner

  functional-test:
    docker:
      - image: cypress/base:8
      - image: aceleradora-tw/esqueleto-ci-runner

    working_directory: ~/repo

    steps:
      - checkout

      - run: cypress run testes-funcionais/cypress

  integration-deploy:
      docker:
        - image: buildpack-deps:trusty
      steps:
        - checkout
        - run:
            name: Deploy para o ambiente de integracao
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_INTEGRATION_APP_NAME.git master

workflows:
  version: 2
  deploy-to-integration:
    jobs:
      - build
      - integration-deploy:
          requires:
            - build
          filters:
            branches:
              only: master
