version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-node-browsers-legacy

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: gradle dependencies
      - run: gradle test

  deploy_integracao:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_INTEGRATION_APP_NAME.git master

  teste_de_fumaca:
    docker:
      - image: cypress/base:8
    steps:
      - run: npm install
      - run: $(npm bin)/cypress run

workflows:
  version: 2
  build_padrao:
    jobs:
      - build
    # - deploy_integracao:
    # -  requires:
    # -    - build
      - teste_de_fumaca
    #     requires:
    #       - deploy_integracao
