version: 2.1
jobs:
  build:
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gr
  orbs:
    cypress: cypress-io/cypress@1.5.0

  deploy-integracao:
    steps:
      - checkout
      - run:
          name: Deploy para o ambiente de integracao
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_INTEGRATION_APP_NAME.git master

  teste-de-fumaca:

    command: |
      git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_INTEGRATION_APP_NAME.git master
orbs:
  cypress: cypress-io/cypress@1.5.0

workflows:
  standard-build:
    jobs:
      - cypress/run:
          requires:
            - cypress/install
      - deploy-integracao:
        requires:
          - build