version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-node-browsers-legacy

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: gradle dependencies
      - run: gradle test

  deploy_integracao:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master

  teste_de_fumaca:
    docker:
      - image: cypress/included:3.3.0
    steps:
      - checkout
      - run: cypress run

workflows:
  version: 2
  build_padrao:
    jobs:
      - build
      - deploy_integracao:
          requires:
            - build
          filters:
            branches:
              only: master
      - teste_de_fumaca:
          requires:
            - deploy_integracao
