version: 2
jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test

      - run: gradle assemble

      - run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - run: docker build -f ci-runner.docker -t aceleradoratw/esqueleto-ci-runner .

      - run: docker push aceleradoratw/esqueleto-ci-runner

  functional-tests:
    docker:
      - image: cypress/base:8
      - image: aceleradoratw/esqueleto-ci-runner

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm --prefix testes-funcionais install --verbose

      - run: npx cypress run cypress/integration

  integration-deploy:
      docker:
        - image: buildpack-deps:trusty
      steps:
        - checkout
        - run:
            name: Deploy para o ambiente de integracao
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_INTEGRATION_APP_NAME.git master

workflows:
  version: 2
  standard-build:
    jobs:
      - build
      - functional-tests:
          requires:
            - build
      - integration-deploy:
          requires:
            - build
          filters:
            branches:
              only: master
